### ISSUE TITLE
Online or Offline?

### ISSUE THREAD

**Issue by he-nantian** [yk7333/d3po#11]
Is the algorithm offline or online? What I wonder is the training dataset is fixed or generated before each epoch.

**Comment by he-nantian** [comment]
I find some of the descriptions in your paper mismatches your code. Specifically, in your arxiv v3, it seems that the sampling and judgement procedures are in the training loop, which is indicated in line 3-22 in Algorithm 1 and line 4-6 in Section 5.2. However, in your code, the sampling and judgement procedures are separately ahead of the training procedure, and the model is fine-tuned using a fixed dataset. Is there any information I am missing? Thank you for your time!

**Comment by yk7333** [comment]
During each training round, as illustrated in lines 3-22 of Algorithm 1, we first sample images and then proceed with the training process after obtaining feedback from the web. The code sequence involves sampling first and then training, which are conducted as separate steps. Once the sampling-feedback-training cycle is completed, we use the current model as the reference model for the next round of training, conducting a total of N rounds, as specified in line 2 of Algorithm 1. Since we sample images using the current model in each round, rather than pre-sampling all images before training, our method can be considered as an iterative N-round online approach. To make the algorithm more online, one could reduce the number of images sampled in each round and increase the total number of iterations to achieve a more online effect. However, if human feedback is utilized, this might lead to significant time costs due to the increased number of iterations.

**Comment by he-nantian** [comment]
That makes sense. Thank you very much. By the way, have you conducted any experiments to compare the iterative N-round online approach with a totally offline approach as Diffusion-DPO utilizes? I doubt the necessity of this configuration since it is more time-consuming.

**Comment by yk7333** [comment]
I'm sorry that I haven't conducted comparative experiments related to Diffusion-DPO. The idea behind D3PO is that all data is generated by the model, whereas Diffusion-DPO still requires a pre-existing dataset, which creates a certain gap between the two. You might try updating only one step in the denoising process for each sample to align the speed more closely with Diffusion-DPO. Currently, I am engaged in other reinforcement learning research projects, so I apologize for not being able to conduct further experiments.

**Comment by he-nantian** [comment]
I understand. My concern has been addressed and I will close this issue. Thank you for your time.
